language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
   - "pip install -r requirements.txt -e ."
   - "pip install nose2 --allow-external"
# command to run tests, e.g. python setup.py test
script:  "nose2"